# Perth - as per http://www.whitecollar.com.au/perth_regions.pdf

# rails c 
# load './db/scrips/perth.rb'

# CBD
Area.create :name => "perth city", :code => "6000"
Area.create :name => "highgate", :code => "6003"
Area.create :name => "east perth", :code => "6004"
# Area.create :name => "kings park", :code => "6005"

# South East Perth (6100 - 6147)
Area.create :name => "burswood", :code => "6100"
Area.create :name => "carlisle", :code => "6101"
Area.create :name => "bentley", :code => "6102"
Area.create :name => "rivervale", :code => "6103"
Area.create :name => "ascot", :code => "6104"
Area.create :name => "cloverdale", :code => "6105"
Area.create :name => "welshpool", :code => "6106"
Area.create :name => "beckenham", :code => "6107"
Area.create :name => "thornlie", :code => "6108"
Area.create :name => "maddington", :code => "6109"
Area.create :name => "gosnells", :code => "6110"
Area.create :name => "ashendon", :code => "6111"
Area.create :name => "armadale", :code => "6112"
Area.create :name => "langford", :code => "6147"

# South West Perth (6148 - 6170)
Area.create :name => "ferndale", :code => "6148"
Area.create :name => "bullcreek", :code => "6149"
Area.create :name => "batemen", :code => "6150"
Area.create :name => "kensington", :code => "6151"
Area.create :name => "como", :code => "6152"
Area.create :name => "applecross", :code => "6153"
Area.create :name => "alfred cove", :code => "6154"
Area.create :name => "canning vale", :code => "6155"
Area.create :name => "attadale", :code => "6156"
Area.create :name => "bicton", :code => "6157"
Area.create :name => "east fremantle", :code => "6158"
Area.create :name => "fremantle", :code => "6160"
Area.create :name => "rottnest island", :code => "6161"
Area.create :name => "beaconsfield", :code => "6162"
Area.create :name => "bibra lake", :code => "6163"
Area.create :name => "atwell", :code => "6164"
Area.create :name => "hope valley", :code => "6165"
Area.create :name => "coogee", :code => "6166"
Area.create :name => "anketell", :code => "6167"
Area.create :name => "leda", :code => "6170"

# North West Perth (6007 - 6159)
Area.create :name => "leederville", :code => "6007"
Area.create :name => "daglish", :code => "6008"
Area.create :name => "crawley", :code => "6009"
Area.create :name => "claremont", :code => "6010"
Area.create :name => "cottesloe", :code => "6011"
Area.create :name => "mosman park", :code => "6012"
Area.create :name => "floreat", :code => "6014"
Area.create :name => "city beach", :code => "6015"
Area.create :name => "glendalough", :code => "6016"
Area.create :name => "herdsman", :code => "6017"
Area.create :name => "churchlands", :code => "6018"
Area.create :name => "scarborough", :code => "6019"
Area.create :name => "carine", :code => "6020"
Area.create :name => "hamersly", :code => "6022"
Area.create :name => "duncraig", :code => "6023"
Area.create :name => "greenwood", :code => "6024"
Area.create :name => "craigie", :code => "6025"
Area.create :name => "kingsley", :code => "6026"
Area.create :name => "beldon", :code => "6027"
Area.create :name => "burns beach", :code => "6028"
Area.create :name => "trigg", :code => "6029"
Area.create :name => "north fremantle", :code => "6159"
Area.create :name => "nedlands", :code => "6907"

# North East Perth (6006 - 6062)
Area.create :name => "north perth", :code => "6006"
Area.create :name => "balcatta", :code => "6021"
Area.create :name => "coolbinia", :code => "6050"
Area.create :name => "maylands", :code => "6051"
Area.create :name => "bedford", :code => "6052"
Area.create :name => "bayswater", :code => "6053"
Area.create :name => "ashfield", :code => "6054"
Area.create :name => "dianella", :code => "6059"
Area.create :name => "joondanna", :code => "6060"
Area.create :name => "balga", :code => "6061"
Area.create :name => "embleton", :code => "6062"

# Serpentine - Jarrahdale (6121 - 6126)
Area.create :name => "oakford", :code => "6121"
Area.create :name => "byford", :code => "6122"
Area.create :name => "mundijong", :code => "6123"
Area.create :name => "jarrahdale", :code => "6124"
Area.create :name => "keysbrook", :code => "6126"

# Kalamunda
Area.create :name => "HighWycombe", :code => "6057"
Area.create :name => "forrestfield", :code => "6058"
Area.create :name => "Bickley", :code => "6076"

# Mundaring (6070 - 6558)
Area.create :name => "darlington", :code => "6070"
Area.create :name => "glen forrest", :code => "6071"
Area.create :name => "mahogany creek", :code => "6072"
Area.create :name => "mundaring", :code => "6073"
Area.create :name => "sawyers valley", :code => "6074"
Area.create :name => "parkerville", :code => "6081"
Area.create :name => "bailup", :code => "6082"
Area.create :name => "beechina", :code => "6556"
Area.create :name => "wooroloo", :code => "6558"

# Swan (6055 - 6090)
Area.create :name => "caversham", :code => "6055"
Area.create :name => "baskerville", :code => "6056"
Area.create :name => "beechboro", :code => "6063"
Area.create :name => "ballajura", :code => "6066"
Area.create :name => "callacabardee", :code => "6067"
Area.create :name => "whiteman", :code => "6068"
Area.create :name => "avely", :code => "6069"
Area.create :name => "lexia", :code => "6079"
Area.create :name => "gidgegannup", :code => "6083"
#Area.create :name => "avon valley national park", :code => "6084" ?
Area.create :name => "malaga", :code => "6090"

# Rockingham (6168 - 6182)
Area.create :name => "cooloongup", :code => "6168"
Area.create :name => "safety bay", :code => "6169"
Area.create :name => "baldivis", :code => "6171"
Area.create :name => "port kennedy", :code => "6172"
Area.create :name => "secret harbour", :code => "6173"
Area.create :name => "golden bay", :code => "6174"
Area.create :name => "singleton", :code => "6175"
Area.create :name => "karnup", :code => "6176"
Area.create :name => "keralup", :code => "6182"

# Wanneroo (6030 - 6078)
Area.create :name => "clarkson", :code => "6030"
Area.create :name => "banksia grove", :code => "6031"
Area.create :name => "nowergup", :code => "6032"
Area.create :name => "carabooda", :code => "6033"
Area.create :name => "yanchep", :code => "6035"
Area.create :name => "butler", :code => "6036"
Area.create :name => "two rocks", :code => "6037"
Area.create :name => "alexander heights", :code => "6064"
Area.create :name => "ashby", :code => "6065"
Area.create :name => "gnangara", :code => "6077"
Area.create :name => "mariginiup", :code => "6078"