Subject.create :name => "music", :code => "music"
Subject.create :name => "business", :code => "business"
Subject.create :name => "humanities", :code => "humanities"
Subject.create :name => "english", :code => "english"
Subject.create :name => "science", :code => "science"
Subject.create :name => "maths", :code => "maths"