default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # database: <%= ENV["DB_NAME"] %>
  host:     <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: tutorial_academy_development

test:
  <<: *default
  database: tutorial_academy_test

production:
  <<: *default
  database: tutorial_academy_production
  # password: <%= ENV['DATABASE_PASSWORD'] %>
