# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27b8895061e6d0446eebd64ef18d55020ce2c146d7165f99f20bf2af5c1fe4bcaeb9ecf37f33f00b62686c0670d562c909bf5263e275364effc2850cb007c0df

test:
  secret_key_base: e1c1e17f28c7e170e0a87023ac9bd558e70567cecb84f899a124f3ca111db91a2a10a9f4c57f5d2dddc0fe835656c7db7ecf272535868228ab332142710ce798

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
