module ApplicationHelper
  # 0 = tutor
  # 1 = student

  def resource_name(user)
    if user == 0
      :tutor
    else
      :student
    end
  end

  def resource(user)
    if user == 0
      @resource ||= Tutor.new
    else
      @resource ||= Student.new
    end
  end

  def devise_mapping(user)
    @devise_mapping ||= Devise.mappings[resource_name(user)]
  end

  # Check if the current page was generated by devise (would be in the following controllers)
  def devise_page
    if 
      controller_name == 'sessions' or
      controller_name == 'registrations' or
      controller_name == 'confirmations' or
      controller_name == 'passwords'

      return true
    end

    return false
  end
end
