apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db-volume
  labels:
    app: postgres-db-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
