apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorialacademy
  labels:
    tier: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tutorialacademy
      tier: web-app
  template:
    metadata:
      labels:
        app: tutorialacademy
        tier: web-app
    spec:
      containers:
      - name: tutorialacademy
        image: braydenneale/tutorialacademy
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: app-config
